name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1

      - name: Azure CLI Login
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
          az account set --subscription $AZURE_SUBSCRIPTION_ID

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Get Terraform Outputs
        working-directory: terraform
        id: terraform_outputs
        run: |
          echo "acr_admin_password=$(terraform output -raw acr_admin_password)" >> $GITHUB_ENV
          echo "acr_login_server=$(terraform output -raw acr_login_server)" >> $GITHUB_ENV
          echo "acr_admin_username=$(terraform output -raw acr_admin_username)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      - name: Log in to Azure Container Registry
        run: |
          echo ${{ env.acr_admin_password }} | docker login ${{ env.acr_login_server }} -u ${{ env.acr_admin_username }} --password-stdin

      - name: Push Docker image to Azure Container Registry
        run: |
          docker tag myapp:latest ${{ env.acr_login_server }}/myapp:latest
          docker push ${{ env.acr_login_server }}/myapp:latest
