name: Trigger auto deployment for lftran-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/lftran-container-app-AutoDeployTrigger-767b3f8d-ea02-4617-96a5-3a186b14989f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.LFTRANCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LFTRANCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LFTRANCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.LFTRANCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LFTRANCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: lftran-container-app
          resourceGroup: sameesa234
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


